name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/**.java"
  pull_request:
    branches: [main]
    paths:
      - "src/**.java"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Compile .class
        run: javac -verbose *.java
        working-directory: src/
      - name: Create .jar
        run: jar cvfe build.jar Main *.class
        working-directory: src/
      - name: Upload .jar
        uses: actions/upload-artifact@v2
        with:
          name: build.jar
          path: src/build.jar
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: remove old docs
        run: git rm -r docs
        continue-on-error: true
      - run: javadoc -d docs src/*.java
      - name: publish new docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Auto generated docs"
          git push
